### ISSUE TITLE
IoT on AWS

### ISSUE THREAD

**Issue by GJS2162** [FOSS-Community/OSS-Fest#1]
### Title

IoT on AWS

### Describe your Talk

I will show how to send data from an DHT-22 sensor to the cloud using ESP-32.
In this I will show them how to connect the sensor to ESP-32 and explain the code, like how hardware will be connected to the cloud.
Then I will demonstrate live data(Temperature and Humidity).
To make the session interactive I will ask them to come and interact with the sensors so that they can see the readings changing.
I want that students should see that if they are going to learn about Cloud or IoT or anything else in the future then how that things can work in real scenario.

### Pre-requisites & reading material

No pre requisites.

### Time required for the talk

30-40 min

### Any comments

I want them to enjoy rather than mug up things.
I want that they should not have fear in future that, Oh Cloud is tough!! or dealing with sensors is hard.

**Comment by akshatcoder-hash** [comment]
Hey @GJS2162 
As you want to take a workshop, you can submit your proposal [here](https://github.com/FOSS-Community/talks/issues/new/choose) for the weekly talks session.
I am closing this issue from here.
:)
